### ISSUE TITLE
Flex-伸缩布局-flex-常用标签

### ISSUE THREAD

**Issue by HaoleiQ** [HaoleiQ/Note#20]
Flex-伸缩布局-flex-常用标签
```css
.flex {
  display: -webkit-box;
  display: -webkit-flex;
  display: flex;
}

.flex-1 {
  -webkit-box-flex: 1;
  -webkit-flex: 1;
  flex: 1;
}

.flex-col {
  -webkit-box-orient: vertical;
  -webkit-flex-flow: column;
  flex-direction: column;
}

.flex-col-rev {
  -webkit-box-orient: vertical;
  -webkit-flex-flow: column-reverse;
  flex-flow: column-reverse;
}

.f-just-c {
  justify-content: center;
}

.f-just-around {
  justify-content: space-around;
}

.f-just-between {
  justify-content: space-between;
}

.align-center {
  text-align: center;
}

.f-wrap-w {
  flex-wrap: wrap;
}

.inline-flex{
  display:inline-flex;
}
```
